# Generated by Django 5.1.4 on 2025-01-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pt_register',
            name='drName',
        ),
        migrations.DeleteModel(
            name='Dr_details',
        ),
        migrations.DeleteModel(
            name='Pt_register',
        ),
    ]
