# Generated by Django 5.1.4 on 2025-01-11 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0004_alter_dr_details_phone_alter_pt_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_register',
            name='booking',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 8, 32, 34, 460891, tzinfo=datetime.timezone.utc)),
        ),
    ]
