# Generated by Django 5.1.4 on 2025-01-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0009_remove_dr_details_id_alter_dr_details_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pt_register',
            name='drName',
        ),
        migrations.DeleteModel(
            name='Dr_details',
        ),
        migrations.DeleteModel(
            name='Pt_register',
        ),
    ]
