# Generated by Django 5.1.4 on 2025-01-11 08:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataHandle', '0010_remove_pt_register_drname_delete_dr_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dr_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pt_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('booking', models.DateTimeField(default=datetime.datetime(2025, 1, 11, 8, 56, 58, 507186, tzinfo=datetime.timezone.utc))),
                ('drName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataHandle.dr_details')),
            ],
        ),
    ]
